fecha

diff --git a/.github/workflows/taller2.yaml b/.github/workflows/taller2.yaml
--- a/.github/workflows/taller2.yaml
+++ b/.github/workflows/taller2.yaml
@@ -65,11 +65,11 @@ jobs:
             url=$(echo "$response" | jq -r '.url')
           fi
 
-          if [ "$url" != "null" ]; then
-            echo "url=$url" >> $GITHUB_OUTPUT
-          else
-            echo "No se encontró imagen para la fecha: $fecha"
+          if [ "$url" == "null" ] || [ -z "$url" ]; then
+            echo "No se encontró imagen para la fecha: $fecha o URL está vacía."
             exit 0
+          else
+            echo "url=$url" >> $GITHUB_OUTPUT
           fi
 
       - name: Descargar imagen desde la URL
@@ -77,7 +77,17 @@ jobs:
           url="${{ steps.obtener_url.outputs.url }}"
           output_path="images/img-${{ matrix.fecha }}.jpg"
           echo "Descargando imagen desde: $url"
-          curl -L "$url" -o "$output_path"
+
+          # Comprobar si la URL es válida
+          if [[ -z "$url" ]]; then
+            echo "Error: URL de la imagen está vacía. No se puede descargar."
+            exit 1
+          fi
+
+          curl -L "$url" -o "$output_path" || {
+            echo "Error al descargar la imagen desde $url"
+            exit 1
+          }
 
       - name: Subir imágenes como artefactos
         uses: actions/upload-artifact@v4
